version: '3.7'
networks:
  test:
    external:
      name: dev
services:
  ca-org1:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org3
      - FABRIC_CA_SERVER_CSR_CN=ca-org3
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7056
      - FABRIC_CA_SERVER_DEBUG=true
      #- GODEBUG=netdns=go
    ports:
      - 7056:7056
    command: sh -c 'fabric-ca-server start -d -b ca-org3-admin:ca-org3-adminpw --port 7056'
    volumes:
      - ../../organizations/fabric-ca/org3:/etc/hyperledger/fabric-ca-server
    container_name: ca_org3
    networks:
      - test
